[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "grpc"
url = "http://0.0.0.0:10101"
x_token = ""
kind = "yellowstone"

[[endpoint]]
name = "arpc"
url = "http://0.0.0.0:20202"
x_token = ""
kind = "arpc"

[[endpoint]]
name = "thor"
url = "http://0.0.0.0:50051"
x_token = ""
kind = "thor"
